apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-demo-deployment
  labels:
    app: tekton-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tekton-demo
  template:
    metadata:
      labels:
        app: tekton-demo
    spec:
      containers:
      - name: tekton-demo
        image: __IMAGE__
        ports:
        - containerPort: 8000
      nodeSelector: 
        "beta.kubernetes.io/os": linux
---
apiVersion: v1
kind: Service
metadata:
  name: tekton-demo-svc
spec:
  selector:
    app: tekton-demo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tekton-demo-ingress-rules
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    external-dns.alpha.kubernetes.io/hostname: tekton-demo.aks.srinipadala.xyz
    external-dns.alpha.kubernetes.io/target: aks.srinipadala.xyz
    cert-manager.io/cluster-issuer: letsencrypt   
spec:
  tls:
    - hosts:
      - tekton-demo.aks.srinipadala.xyz
      secretName: tls-tekton-demo-secret
  rules:
    - host: tekton-demo.aks.srinipadala.xyz
      http:
       paths:
       - backend:
            serviceName: tekton-demo-svc
            servicePort: 80
         path: /(.*)
